### ISSUE TITLE
Schema sidebar should show which columns have secondary indexes

### ISSUE THREAD

**Issue by zuk** [AnthonyBobsin/conduit#3]
When writing CQL queries it's helpful to know which secondary indexes are available. Currently only the primary key is shown. Would be great if there was some sort of indicator next to columns that have secondary indexes. Maybe they could be shown in italics? Or maybe have some other icon in front of them. How about ☞? (index finger... index...)

**Comment by AnthonyBobsin** [comment]
I really like the index finger idea for the icon, just implemented and pushed to master
